deleted last_modified function & datetime package in models.py
planetlabs/planet-client-python pull request #335
Opened 2021-11-04 16:33 UTC by mkshah605

Deleted both the last_modified function and the datetime package in the models.py file, as neither of them are being used. This change successfully passed nox testing.

2021-11-19 15:36 UTC, kevinlacaille reviewed
I was wrong, I think we should keep this function in! See my comments for my reasoning 👍 

Now, I think we should add a test for this function in `tests/unit/test_models.py`!

2021-11-19 15:36 UTC, kevinlacaille commented on planet/models.py
> -    def last_modified(self):
I believe I was wrong. I think we should keep this function. Although this planet module doesn't call for this function, `last_modified()`, a user might actually want to use this function. So, I suggest putting it back in along with the `datetime` module.

Now, my first comment still stands - we need to either change `datetime.strptime()` to `datetime.datetime.strptime()`. Or you can do `from datetime import datetime`, then `datetime.strptime()` will work :)

2021-11-19 15:36 UTC, kevinlacaille commented on planet/models.py
> -import datetime
From my comment bellow, this should go back in either as is or as `from datetime import datetime` - chef's choice!

2021-11-20 00:03 UTC, jreiberkyle requested changes
The new tests are focused and clear and cover the expected variations. They are great. I suggest removing all of the unrelated changes, ie the removal of empty lines.

2021-11-20 00:03 UTC, jreiberkyle commented on planet/models.py
> -
Is there a reason these empty lines were removed? Their presence increases readability of the docstrings. I suggest undoing all the 'remove empty line' changes

2021-11-24 20:25 UTC, kevinlacaille approved these changes
Looks good to me! 🎉

2021-12-15 01:00 UTC, jreiberkyle approved these changes
Looks great. Nicely done!

2021-12-15 18:45 UTC, merged