Validated item type with specs module
planetlabs/planet-client-python pull request #713
Opened 2022-10-12 18:01 UTC by kevinlacaille

Addresses @jreiberkyle's two comments ([comment 1](https://github.com/planetlabs/planet-client-python/pull/695/files/4935b11afab9a5c731831f6930d5bcc2ab5783fd#r977967575), [comment 2](https://github.com/planetlabs/planet-client-python/pull/695/files/4935b11afab9a5c731831f6930d5bcc2ab5783fd#r977970613)).

Closes #690

2022-10-12 20:01 UTC, jreiberkyle commented
@kevinlacaille I'm a bit concerned that a linting issue was able to pass CI checks and make it into main. I'm going to spend a little bit of time seeing if I can track down the cause. I can confirm that `main` branch as it is does not pass a local run of `nox -s lint`

2022-10-12 20:21 UTC, jreiberkyle commented
for now, I'm going to just chalk that issue up to the IP PRs having their checks run prior to the flake8 lint change. Will keep this in mind but I feel good that the CI of this PR picked up the linting issue.

2022-10-12 23:09 UTC, jreiberkyle requested changes
The CLI output does not match what is requested in #690, this can likely be fixed by raising `click.BadParameter` instead of `SpecificationException`

2022-10-12 23:09 UTC, jreiberkyle commented on planet/cli/data.py
> +    return item_types
An added benefit of adding the output to the PR desc: easy to confirm or deny that the actual output is what is desired in #690. Currently, it's not yet a match.

2022-10-13 18:44 UTC, jreiberkyle commented on planet/cli/data.py
> +    return item_types
here's an example of catching/throwing: https://github.com/planetlabs/planet-client-python/blob/3aa079918b098e9ff6bae346f64d8bd87db5a9d7/planet/cli/orders.py#L301

2022-10-14 16:20 UTC, kevinlacaille commented on tests/integration/test_orders_cli.py
> +    error_msg = "Usage: main orders request [OPTIONS] ITEM_TYPE BUNDLE"
You got it!

2022-10-14 16:23 UTC, kevinlacaille commented on planet/cli/data.py
> +    return item_types
Ah yes, I didn't catch this - thank you for the example!

2022-10-14 16:25 UTC, kevinlacaille commented on tests/integration/test_orders_cli.py
> +    error_msg = "Usage: main orders request [OPTIONS] ITEM_TYPE BUNDLE"
I completely agree, but this isn't an addition to the Data CLI PR, it's just a linting error I've resolved in this PR. If we want to change the Orders CLI's error message, I'd say let's create a new ticket for it :)

2022-10-14 16:31 UTC, kevinlacaille commented on planet/cli/data.py
> +    return item_types
Catching `specs.SpesificationError` and raising `click.BadParameter` does indeed solve the problem - thanks @jreiberkyle !

2022-10-14 18:44 UTC, jreiberkyle approved these changes
looks great! And thank you so much for adding the behavior change to the PR desc. super helpful!

2022-10-14 18:45 UTC, merged