Data CLI documentation updates
planetlabs/planet-client-python pull request #891
Opened 2023-03-22 04:46 UTC by cholmes

**Related Issue(s):**

Closes #886, #885, #615

**Proposed Changes:**

For inclusion in changelog (if applicable):

1. Documented CLI for data stats, saved search and asset functionality

Not intended for changelog:

1. Asset had some documentation, but I updated to a consistent style / voice with the rest of the docs.

*NOTE:* - The new documentation in this PR will need to be updated when #884 lands, and also if #890 and #887 land. Changes should be simple/easy, but we should be sure to update. I originally started out the docs anticipating #884, but then I wasn't sure if the other two would land, so seemed easiest to just make the docs so they can merge immediately. Then if #884 lands first we can update this PR, and if this lands first we can update that PR.

**PR Checklist:**

- [x] This PR is as small and focused as possible
- [x] If this PR includes proposed changes for inclusion in the changelog, the title of this PR summarizes those changes and is ready for inclusion in the Changelog.
- [] I have updated docstrings for function changes and docs in the 'docs' folder for user interface / behavior changes
- [] This PR does not break any examples or I have updated them

**(Optional) @mentions for Notifications:**

2023-03-22 16:13 UTC, JuLeeAtPlanet commented on docs/cli/cli-data.md
> -
On line 149, suggest changing:

The lets you do things like get the id of the most recent skysat image taken (that you have download access to):

To:

This lets you do things like get the ID of the most recent SkySat image taken (and that you have permissions to download):

2023-03-22 16:15 UTC, JuLeeAtPlanet commented on docs/cli/cli-data.md
> -## `data asset` command basics
On line 293, suggest changing:

which can be interested to inspect

to:

which can be interesting to inspect

2023-03-22 16:18 UTC, JuLeeAtPlanet commented on docs/cli/cli-data.md
> +Note that the API does not support an 'all time' interval to get the total of all collections for an area, but
There are 12 sentences that begin with "Note..." Remove some if they're not really notifications that need to be emphasized. For example, suggest changing this to:

```suggestion
The API does not support an 'all time' interval to get the total of all collections for an area, but
```

2023-03-22 16:18 UTC, JuLeeAtPlanet commented on docs/cli/cli-data.md
> +Note though that while some assets activate almost immediately (if another user has requested
```suggestion
While some assets activate almost immediately (if another user has requested
```

2023-03-22 16:19 UTC, JuLeeAtPlanet commented on docs/cli/cli-data.md
> +and also the same [sort](#sort) parameter (`--sort`). Note that you can also run any previous `quick` search.
```suggestion
and also the same [sort](#sort) parameter (`--sort`). You can also run any previous `quick` search. 
```

2023-03-22 16:20 UTC, JuLeeAtPlanet commented on docs/cli/cli-data.md
> +Note you can also delete `quick` searches, which would remove them from your history.
```suggestion
You can also delete `quick` searches, which would remove them from your history.
```

2023-03-22 16:22 UTC, JuLeeAtPlanet requested changes
Please address typos (lines 149 & 329)

2023-03-23 01:20 UTC, cholmes commented
Ok, made all the suggested changes. Note the first two were errors in the original file, not in the PR, so in the future it'd be easier if those are just done in a separate review. But went ahead and got them all in.

2023-03-23 03:40 UTC, JuLeeAtPlanet approved these changes

2023-03-23 03:42 UTC, JuLeeAtPlanet approved these changes

2023-03-23 03:43 UTC, JuLeeAtPlanet approved these changes

2023-03-24 19:21 UTC, cholmes commented
Updated for the syntax updates (#884, #887, #890). Note one still has to be merged. I'm not sure exactly how the docs builds work, but we probably don't want to publish this update until the next version is actually released. Note that #890 (Pr #898) is not yet closed, but I documented here anticipating that it would.

2023-04-11 03:26 UTC, merged