Added an --ids-only option.
planetlabs/planet-client-python pull request #940
Opened 2023-04-26 20:19 UTC by kevinlacaille

**Related Issue(s):**

Closes #645 

**Proposed Changes:**

For inclusion in changelog (if applicable):

1. Added a flag, `ids-only`, which returns only the item IDs from a search.

Not intended for changelog:

1. 

**Diff of User Interface**

Old behavior:
```console
❯ planet data search psscene --limit 10 | jq .id  
"20230426_134930_74_242d"
"20230426_170754_42_2423"
"20230426_160116_58_2430"
"20230426_083418_51_24c8"
"20230426_150139_34_2254"
"20230426_155734_58_2430"
"20230426_131930_22_247f"
"20230426_171340_13_2423"
"20230426_103723_01_2465"
"20230426_073224_63_24a8"
```

New behavior:
```console
❯ planet data search psscene --limit 10 --ids-only
"20230426_134930_74_242d"
"20230426_170754_42_2423"
"20230426_160116_58_2430"
"20230426_083418_51_24c8"
"20230426_150139_34_2254"
"20230426_155734_58_2430"
"20230426_131930_22_247f"
"20230426_171340_13_2423"
"20230426_103723_01_2465"
"20230426_073224_63_24a8"
```

**PR Checklist:**

- [x] This PR is as small and focused as possible
- [x] If this PR includes proposed changes for inclusion in the changelog, the title of this PR summarizes those changes and is ready for inclusion in the Changelog.
- [] I have updated docstrings for function changes and docs in the 'docs' folder for user interface / behavior changes
- [] This PR does not break any examples or I have updated them

**(Optional) @mentions for Notifications:**

2023-04-26 21:13 UTC, cholmes commented
I realized I never explained this in the original ticket, but the key for this is that the output can be directly piped into the orders request command. So it needs to remove the " and replace the newlines with commas. So output should be like `20230120_003217_79_24ab,20230120_003215_49_24ab,20230120_003213_19_24ab,20230120_003210_89_24ab,20230128_003142_04_24ab`

2023-04-27 23:20 UTC, sgillies commented on planet/cli/data.py
> +                echo_json(item, pretty)
@kevinlacaille In #645 I'm pushing back on this feature request, but if we did it, this is completely sound. Append to list oe print to terminal, this is easy to read and understand. It's symmetry in action.

2023-05-04 17:48 UTC, sgillies commented on planet/cli/orders.py
> +@click.option('--ids-only', is_flag=True, help='Returns only the item IDs.')
@kevinlacaille #645 is only about getting a list of ids from search. Let's not extend to the orders CLI here. Can you remove the changes to planet/cli/orders.py?

2023-05-04 17:54 UTC, sgillies commented on planet/cli/data.py
> +        item_ids = []
```suggestion
In #645 we've recognized that search results may cover multiple item_types and that mixing their ids together sets a user up for failure. @kevinlacaille what would you think about this?

```suggestion
        if ids_only and len(item_types) > 1:
            raise ClickException("item id output is not allowed when multiple item types have been searched.")

        item_ids = []
```

2023-05-04 17:55 UTC, sgillies requested changes
@kevinlacaille I'm in favor, but would like to see 2 changes.

2023-05-04 18:19 UTC, jreiberkyle commented
I am against merging this at this time. Lets have more discussion.

2026-07-20 16:29 UTC, closed without merging